version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/run4fun?schema=public
      - PORT=3000
    depends_on:
      - db
    # For development, enable volume mount
    # For production, you might want to comment these out
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist  # Preserve the dist directory from container


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=run4fun
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: